# Generated by Django 4.0.4 on 2022-05-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha',
            new_name='fecha_salida',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
