# Generated by Django 4.0.4 on 2022-05-30 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_rename_fecha_viaje_fecha_salida_viaje_fecha_regreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
